// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA64TzicCX1-Refru77ORxn-UCpdaattJA',
    appId: '1:129362309764:web:61bd6e88a300598c94c8d1',
    messagingSenderId: '129362309764',
    projectId: 'kiliride',
    authDomain: 'kiliride.firebaseapp.com',
    storageBucket: 'kiliride.firebasestorage.app',
    measurementId: 'G-X5CPJ3QTWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUZOD6329Gh11rzx96X_uoGufafK0G4tI',
    appId: '1:129362309764:android:e782adadd45a72a794c8d1',
    messagingSenderId: '129362309764',
    projectId: 'kiliride',
    storageBucket: 'kiliride.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs5IZP9tw7T4aihrBgTSWqwBUguhcp_SU',
    appId: '1:129362309764:ios:4c3718719a72b23694c8d1',
    messagingSenderId: '129362309764',
    projectId: 'kiliride',
    storageBucket: 'kiliride.firebasestorage.app',
    iosBundleId: 'com.example.kiliride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs5IZP9tw7T4aihrBgTSWqwBUguhcp_SU',
    appId: '1:129362309764:ios:4c3718719a72b23694c8d1',
    messagingSenderId: '129362309764',
    projectId: 'kiliride',
    storageBucket: 'kiliride.firebasestorage.app',
    iosBundleId: 'com.example.kiliride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA64TzicCX1-Refru77ORxn-UCpdaattJA',
    appId: '1:129362309764:web:9b82f9cb10f5b8b194c8d1',
    messagingSenderId: '129362309764',
    projectId: 'kiliride',
    authDomain: 'kiliride.firebaseapp.com',
    storageBucket: 'kiliride.firebasestorage.app',
    measurementId: 'G-8390EV4MJP',
  );
}
